apiVersion: 1

policies:
  - orgId: 1
    receiver: appsec-webhook
    group_by: ['alertname', 'severity']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: appsec-webhook
        matchers:
          - severity = critical
        group_wait: 10s
        repeat_interval: 1h
      - receiver: appsec-webhook
        matchers:
          - severity = warning
        group_wait: 30s
        repeat_interval: 4h
