ALTER TABLE users ADD COLUMN IF NOT EXISTS enabled    BOOLEAN   NOT NULL DEFAULT TRUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login TIMESTAMP;

CREATE INDEX IF NOT EXISTS idx_users_enabled ON users(enabled);
